Repository prgrms-fe-devcourse/FEDC5_NodakNodak_Noah, pull requests merged in 2023-12, with the labels that each got.

#4 [FEAT] API 응답타입 선언
  src/types/APIResponseTypes.ts
  src/types/ComponentTypes.ts
Labels: feature

#7 [FEAT] 버튼 컴포넌트 구현!
  src/App.css
  src/App.tsx
  src/components/Button/Index.tsx
  src/components/Button/StyledButton.tsx
  src/components/Button/index.css
  src/index.css
  src/main.tsx
  src/types/ButtonPropsTypes.ts
Labels: feature

#9 [FEAT] Image와 Avatar컴포넌트 구현
  .eslintrc.cjs
  src/components/Avatar/AvatarStyled.ts
  src/components/Avatar/Index.tsx
  src/components/Image/Index.tsx
  src/types/APIResponseTypes.ts
  src/types/AvatarProps.tsx
  src/types/ImageProps.tsx
Labels: feature

#17 [FEAT] Card 컴포넌트 구현
  src/components/Card/CardProps.tsx
  src/components/Card/index.tsx
Labels: feature

#15 [FEAT] onlineBadge 컴포넌트 구현
  src/components/OnlineBadge/StyledBadge.ts
  src/components/OnlineBadge/index.tsx
  src/types/OnlineBadgePropsTypes.ts
Labels: feature

#19 [FIX] Index.tsx 대문자를 소문자로 수정
  src/components/Button/index.tsx
Labels: fix

#25 [FEAT] UserStatusList 컴포넌트 구현
  src/components/Avatar/index.tsx
  src/components/Image/index.tsx
  src/components/OnlineBadge/StyledBadge.ts
  src/components/ScrollBar/StyledScrollBar.ts
  src/components/ScrollBar/index.tsx
  src/components/UserListCard/index.tsx
  src/components/UserListCard/mockUsers.ts
  src/components/UserSnippet/StyledUserSnippet.ts
  src/components/UserSnippet/index.tsx
  src/types/UserListCardTypes.ts
  src/types/UserSnippetProps.ts
Labels: feature

#27 [Refector] 버튼 리팩토링
  src/components/Button/index.tsx
Labels: refactor

#29 [FEAT] Login 페이지 UI
  .gitignore
  api/index.ts
  index.html
  package-lock.json
  package.json
  src/components/Input/InputStyles.ts
  src/components/Input/PasswordInput.tsx
  src/components/Sign/In.tsx
  src/components/Sign/SignStyle.ts
  src/components/Sign/Up.tsx
  src/pages/Login.tsx
  src/styles/GlobalStyle.ts
  src/types/InputProps.ts
Labels: feature

#31 [FEAT] 게시글 Content 뷰로직
  src/components/Avatar/index.tsx
  src/components/PostContent/PostContentStyled.tsx
  src/components/PostContent/index.tsx
  src/components/Text/index.tsx
  src/types/ButtonPropsTypes.ts
  src/types/TextProps.ts
Labels: feature

#36 [FEAT] 게시글 Comment 뷰로직
  src/components/Comment/index.tsx
  src/components/PostComment/index.tsx
Labels: feature

#38 [Feat] create post page component 구현
  src/components/Input/InputStyles.ts
  src/components/Input/index.tsx
  src/pages/PostEditPage/DropdownMenu/DropdownMenuStyled.tsx
  src/pages/PostEditPage/DropdownMenu/index.tsx
  src/pages/PostEditPage/PostEditPage.tsx
  src/pages/PostEditPage/VoteEditBox/VoteEditBoxStyled.tsx
  src/pages/PostEditPage/VoteEditBox/index.tsx
  src/types/InputProps.ts
Labels: feature

#42 [FEAT] 게시글 투표 뷰 로직
  src/components/PostVote/index.tsx
  src/components/Text/index.tsx
  src/pages/userPage/UserPostList.tsx
  src/types/APIResponseTypes.ts
  src/types/AvatarProps.ts
  src/types/ImageProps.ts
Labels: feature

#44 [FEAT] userPage UI제작
  index.html
  package-lock.json
  package.json
  src/assets/Logo.tsx
  src/pages/Index.tsx
  src/pages/NotFound.tsx
  vite.config.ts
Labels: feature

#41 [FEAT] 포스트 카드 구현
  src/components/Avatar/index.tsx
  src/components/PostCard/PostSnippet.tsx
  src/components/PostCard/StyledPostCard.ts
  src/components/PostCard/index.tsx
  src/components/PostCard/mockPosts.ts
  src/types/AvatarProps.ts
  src/types/PostCardTypes.ts
Labels: feature

#49 [FIX] Input component 수정
  src/components/Input/InputStyles.ts
  src/components/Input/PasswordInput.tsx
  src/components/Input/index.tsx
  src/components/PostComment/index.tsx
  src/components/PostVote/index.tsx
  src/components/Sign/In.tsx
  src/components/Sign/SignStyle.ts
  src/components/Sign/Up.tsx
  src/types/InputProps.ts
Labels: fix

#53 [Refactor] 디자인 시스템 컴포넌트 리팩토링
  src/components/Avatar/AvatarProps.ts
  src/components/Avatar/AvatarStyled.ts
  src/components/Avatar/index.tsx
  src/components/Button/ButtonPropsTypes.ts
  src/components/Button/StyledButton.tsx
  src/components/Button/index.css
  src/components/Button/index.tsx
  src/components/Card/CardProps.tsx
  src/components/Card/index.tsx
  src/components/Comment/index.tsx
  src/components/Image/ImageProps.ts
  src/components/Image/index.tsx
  src/components/Input/InputProps.ts
  src/components/Input/InputStyles.ts
  src/components/Input/PasswordInput.tsx
  src/components/Input/index.tsx
  src/components/OnlineBadge/OnlineBadgePropsTypes.ts
  src/components/OnlineBadge/index.tsx
  src/components/Pagination/PaginationTypes.ts
  src/components/Pagination/index.tsx
  src/components/PostCard/PostCardTypes.ts
  src/components/PostCard/index.tsx
  src/components/PostComment/index.tsx
  src/components/PostContent/index.tsx
  src/components/PostVote/index.tsx
  src/components/Text/TextProps.ts
  src/components/Text/index.tsx
  src/components/UserListCard/UserListCardTypes.ts
  src/components/UserListCard/index.tsx
  src/components/UserSnippet/UserSnippetProps.ts
  src/components/UserSnippet/index.tsx
  src/pages/userPage/UserInfo.tsx
  src/pages/userPage/UserPostList.tsx
  src/types/InputProps.ts
Labels: feature

#51 [FEAT] Main 페이지 구현
  src/components/Pagination/PaginationTypes.ts
  src/components/Pagination/index.tsx
  src/components/PostCard/PostCardTypes.ts
  src/components/PostCard/StyledPostCard.ts
  src/components/PostCard/index.tsx
  src/components/PostCard/mockPosts.ts
  src/components/UserSnippet/StyledUserSnippet.ts
  src/pages/mainPage/StyledMain.ts
  src/pages/mainPage/index.tsx
Labels: feature

#57 [FEAT] Header, Footer 컴포넌트 구현
  src/assets/Bell.tsx
  src/components/Badge/BadgeProps.ts
  src/components/Badge/StyledBadge.ts
  src/components/Badge/index.tsx
  src/components/Footer/StyledFooter.ts
  src/components/Footer/index.tsx
  src/components/Header/HeaderProps.ts
  src/components/Header/StyledHeader.ts
  src/components/Header/index.tsx
  src/components/Header/mockChannels.ts
  src/components/LogoWithFontSize/LogoWithFontSizeProps.ts
  src/components/LogoWithFontSize/index.tsx
Labels: feature

#56 [FEAT] Detail 페이지 구현
  src/components/Comment/index.tsx
  src/components/Input/InputStyles.ts
  src/components/Input/PasswordInput.tsx
  src/components/Input/index.tsx
  src/components/Sign/In.tsx
  src/components/Sign/Up.tsx
  src/pages/DetailPage/Dummy.ts
  src/pages/DetailPage/PostComment/index.tsx
  src/pages/DetailPage/PostContent/PostContentStyled.tsx
  src/pages/DetailPage/PostContent/index.tsx
  src/pages/DetailPage/PostVote/index.tsx
  src/pages/DetailPage/index.tsx
Labels: feature, refactor
