Repository prgrms-fe-devcourse/FEDC5_NodakNodak_Noah, pull requests merged in 2024-01, with the labels that each got.

#58 [FEAT] PostEditPage 구현
  src/pages/PostEditPage/DropdownMenu/index.tsx
  src/pages/PostEditPage/VoteEditBox/VoteEditBoxStyled.tsx
  src/pages/PostEditPage/VoteEditBox/index.tsx
  src/pages/PostEditPage/index.tsx
Labels: feature

#62 [FIX] Login/Register 보충
  api/index.ts
  src/components/Sign/In.tsx
  src/components/Sign/SignStyle.ts
  src/components/Sign/Up.tsx
  src/pages/Index.tsx
Labels: fix

#64 [FEAT] 커스텀 훅 구현
  src/hooks/useHover.ts
  src/hooks/useInterval.ts
  src/hooks/useIntervalFn.ts
  src/hooks/useLocalStorage.ts
Labels: feature

#65 [FEAT] assets 파일 추가
  package-lock.json
  package.json
  src/assets/BellIcon.svg
  src/assets/CheckIcon.svg
  src/assets/DefaultImage.jpg
  src/assets/DefaultProfile.jpg
  src/assets/DeleteIcon.svg
  src/assets/DownArrowIcon.svg
  src/assets/InfoIcon.svg
  src/assets/MinusIcon.svg
  src/assets/PlusIcon.svg
  src/assets/RightArrowIcon.svg
  src/assets/TitleLogo.svg
  src/assets/TrashCanIcon.svg
  src/assets/UserIcon.svg
  src/vite-env.d.ts
  svg.d.ts
  tsconfig.json
  vite.config.ts
Labels: feature

#61 [FEAT] SettingModal 제작
  src/pages/SettingModal/Setting.tsx
Labels: feature

#67 [FEAT] 채널 리덕스 스토어 구현
  package-lock.json
  package.json
  src/main.tsx
  src/pages/mainPage/index.tsx
  src/slices/channel.ts
  src/store/index.ts
Labels: feature

#77 [Refector] SettingModal 컴포넌트 속성 수정
  src/pages/SettingModal/Setting.tsx
Labels: refactor

#71 [FEAT] post수정 페이지 구현
  src/main.tsx
  src/pages/PostEditPage/DropdownMenu/index.tsx
  src/pages/PostEditPage/VoteEditBox/index.tsx
  src/pages/PostEditPage/index.tsx
Labels: feature

#76 [Feat] custom 훅 작성
  src/hooks/useHover.ts
  src/hooks/useInterval.ts
  src/hooks/useIntervalFn.ts
  src/hooks/useLocalStorage.ts
  src/hooks/useRafState.ts
  src/hooks/useScroll.ts
Labels: feature

#78 [FEAT] 커스텀 훅 구현 (debounce, timeout, timeoutFn,clickAway)
  src/hooks/useClickAway.ts
  src/hooks/useDebounce.ts
  src/hooks/useTimeout.ts
  src/hooks/useTimeoutFn.ts
Labels: feature

#80 [FEAT] detailPage props수정 및 리덕스 store체계 변경
  src/components/Comment/index.tsx
  src/main.tsx
  src/pages/DetailPage/PostComment/index.tsx
  src/pages/DetailPage/PostContent/index.tsx
  src/pages/DetailPage/index.tsx
  src/pages/mainPage/index.tsx
  src/slices/postDetail.ts
  src/store/index.ts
Labels: feature

#83 [FEAT] Formik 라이브러 적용
  package-lock.json
  package.json
  src/main.tsx
  src/pages/PostEditPage/DropdownMenu/index.tsx
  src/pages/PostEditPage/VoteEditBox/index.tsx
  src/pages/PostEditPage/index.tsx
Labels: feature

#86 [FEAT] 채널 데이터와 home 페이지 연결
  src/App.tsx
  src/components/Header/index.tsx
  src/components/PostCard/PostSnippet.tsx
  src/pages/mainPage/index.tsx
  src/slices/channel.ts
Labels: feature

#90 [FIX] Avatar, Image 기본 이미지 추가
  public/DefaultImage.jpg
  public/DefaultProfile.jpg
  src/components/Avatar/index.tsx
  src/components/Image/index.tsx
Labels: fix

#91 [FEAT] DetailPage 실제데이터 렌더링
  src/components/Comment/index.tsx
  src/pages/DetailPage/PostComment/index.tsx
  src/pages/DetailPage/PostComment/useSelectedComment.ts
  src/pages/DetailPage/PostContent/index.tsx
  src/pages/DetailPage/PostVote/index.tsx
  src/pages/DetailPage/useSelectedPost.ts
Labels: feature

#89 [FEAT] user slice 추가
  src/main.tsx
  src/pages/SettingModal/Setting.tsx
  src/pages/userPage/UserInfo.tsx
  src/pages/userPage/UserPostList.tsx
  src/pages/userPage/index.tsx
  src/slices/user.ts
  src/store/index.ts
  src/types/APIResponseTypes.ts
Labels: feature

#98 [FEAT] Post 수정 페이지 실제 데이터 연결
  src/main.tsx
  src/pages/PostEditPage/DropdownMenu/index.tsx
  src/pages/PostEditPage/PostCreatePage/index.tsx
  src/pages/PostEditPage/PostUpdatePage/index.tsx
  src/pages/PostEditPage/StyledPostEdit.ts
  src/pages/PostEditPage/index.tsx
  src/pages/PostEditPage/useSelectedPost.ts
  src/slices/channel.ts
Labels: feature

#101 [FEAT] 유저 팔로워, home 에서 나가는 라우팅 구현
  src/components/PostCard/PostCardTypes.ts
  src/components/PostCard/PostSnippet.tsx
  src/components/PostCard/index.tsx
  src/components/UserListCard/index.tsx
  src/components/UserSnippet/StyledUserSnippet.ts
  src/components/UserSnippet/UserSnippetProps.ts
  src/components/UserSnippet/index.tsx
  src/hooks/usePagination.ts
  src/main.tsx
  src/pages/DetailPage/index.tsx
  src/pages/mainPage/index.tsx
  src/pages/userPage/UserPostList.tsx
  src/slices/postDetail.ts
  src/slices/postList/utils.ts
  src/slices/user.ts
  src/slices/userList/utils.ts
Labels: feature

#107 [FEAT] 프로필 이미지 변경 기능
  src/components/Avatar/AvatarProps.ts
  src/components/Avatar/index.tsx
  src/components/Image/ImageProps.ts
  src/components/Image/index.tsx
  src/pages/SettingModal/Setting.tsx
  src/pages/userPage/UserInfo.tsx
  src/pages/userPage/UserPostList.tsx
  src/pages/userPage/index.tsx
Labels: feature

#108 [FEAT] 댓글 POST요청 리팩토링 및 auth검증과정 추가
  src/components/PostCard/index.tsx
  src/pages/DetailPage/PostComment/index.tsx
  src/pages/DetailPage/PostComment/useSelectedComment.ts
  src/pages/DetailPage/PostVote/index.tsx
  src/pages/DetailPage/index.tsx
Labels: feature

#109 [FEAT] index 라우팅 수정, detail 페이지기능 추가
  src/components/Header/index.tsx
  src/pages/DetailPage/PostComment/StyledPostComment.ts
  src/pages/DetailPage/PostComment/index.tsx
  src/pages/DetailPage/PostVote/index.tsx
  src/pages/Index.tsx
  src/pages/mainPage/index.tsx
  src/slices/postList/thunks.ts
Labels: feature

#105 [FEAT] setting 데이터 수정 작업
  src/pages/SettingModal/Setting.tsx
  src/slices/user.ts
Labels: feature

#113 [FEAT] postEditPage 수정
  src/assets/DeleteIcon.tsx
  src/pages/PostEditPage/DropdownMenu/DropdownMenuStyled.tsx
  src/pages/PostEditPage/PostCreatePage/index.tsx
  src/pages/PostEditPage/PostUpdatePage/index.tsx
  src/pages/PostEditPage/StyledPostEdit.ts
  src/pages/PostEditPage/VoteEditBox/VoteEditBoxStyled.tsx
  src/pages/PostEditPage/VoteEditBox/index.tsx
Labels: feature

#114 [FEAT] 투표 POST요청 및 중복투표제한
  src/components/Button/ButtonPropsTypes.ts
  src/components/Button/StyledButton.tsx
  src/components/Button/index.tsx
  src/pages/DetailPage/PostComment/index.tsx
  src/pages/DetailPage/PostVote/index.tsx
Labels: feature

#115 [FEAT] progress 컴포넌트 추가 및 데이터 연결
  src/components/PostCard/index.tsx
  src/main.tsx
  src/pages/DetailPage/PostVote/StyledPostVote.ts
  src/pages/DetailPage/PostVote/index.tsx
  src/pages/DetailPage/PostVoteChart/BarChart.tsx
  src/pages/DetailPage/PostVoteChart/index.tsx
  src/pages/DetailPage/index.tsx
  src/pages/userPage/UserPostList.tsx
  src/slices/postList/index.ts
  src/slices/postList/thunks.ts
  src/slices/postList/utils.ts
Labels: feature

#120 fix: 배포 타입에러 수정
  src/components/PostCard/mockPosts.ts
  src/pages/PostEditPage/PostCreatePage/index.tsx
  src/pages/PostEditPage/PostUpdatePage/index.tsx
Labels: fix

#121 배포 오류 수정
  src/components/PostCard/mockPosts.ts
  src/pages/PostEditPage/PostCreatePage/index.tsx
  src/pages/PostEditPage/PostUpdatePage/index.tsx
Labels: fix

#124 Dev
  vercel.json
Labels: fix

#127 Feature/#126 grass component/chae
  src/components/OnlineBadge/StyledBadge.ts
  src/hooks/useSelectedUser.ts
  src/pages/userPage/GrassTable.tsx
Labels: feature

#130 [FEAT] 팔로우 기능 추가
  src/hooks/useSelectedFollowData.ts
  src/hooks/useSelectedMyInfo.ts
  src/pages/userPage/SettingFollowButton.tsx
  src/pages/userPage/UserInfo.tsx
  src/pages/userPage/index.tsx
  src/slices/follow/constants.ts
  src/slices/follow/followType.ts
  src/slices/follow/index.ts
  src/slices/follow/thunk.ts
  src/slices/userList/utils.ts
  src/store/index.ts
Labels: feature

#132 [FIX] setting 레이아웃 수정, 라우팅 처리, 동적 토큰 처리 fix
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/refactor.md
  src/pages/SettingModal/Setting.tsx
Labels: fix

#134 [FEAT] 투표 후보 중복 방지 및 추가 기능 구현
  src/assets/DeleteIcon.tsx
  src/assets/DownArrowIcon.tsx
  src/pages/PostEditPage/DropdownMenu/DropdownMenuStyled.tsx
  src/pages/PostEditPage/DropdownMenu/index.tsx
  src/pages/PostEditPage/PostCreatePage/index.tsx
  src/pages/PostEditPage/PostUpdatePage/index.tsx
Labels: feature

#135 [FEAT] 알림기능 구현
  src/assets/Bell.tsx
  src/components/Header/index.tsx
  src/components/Notification/index.tsx
  src/components/NotificationCardBell/StyledNotification.ts
  src/components/NotificationCardBell/index.tsx
  src/components/NotificationCardBell/mockNotifications.ts
  src/hooks/useSelectedNotifications.ts
  src/hooks/useSelectedPostDetail.ts
  src/pages/DetailPage/PostComment/index.tsx
  src/pages/DetailPage/PostVote/index.tsx
  src/slices/notification/constants.ts
  src/slices/notification/index.ts
  src/slices/notification/notificationType.ts
  src/slices/notification/thunk.ts
  src/store/index.ts
Labels: feature

#138 [FEAT] home 페이지 전체 게시글 추가
  src/App.tsx
  src/components/Header/HeaderProps.ts
  src/components/Header/index.tsx
  src/hooks/usePagination.ts
  src/main.tsx
  src/pages/mainPage/index.tsx
  src/slices/channel.ts
  src/slices/postList/index.ts
  src/slices/postList/thunks.ts
Labels: feature

#142 [FIX] userPage, setting 뷰 로직 수정
  src/assets/MailIcon.tsx
  src/main.tsx
  src/pages/SettingModal/Setting.tsx
  src/pages/userPage/UserPostList.tsx
  src/pages/userPage/index.tsx
Labels: fix

#140 [Fix] Serverless 걷어내기
  api/index.ts
  package-lock.json
  package.json
  src/components/Sign/In.tsx
  src/components/Sign/Up.tsx
  src/pages/PostEditPage/PostUpdatePage/index.tsx
Labels: fix

#144 [FEAT] 프로필 아이콘 클릭 시 드롭다운 나오는 기능
  src/components/Avatar/AvatarProps.ts
  src/components/Avatar/index.tsx
  src/components/DropdownMenu/DropdownMenuStyled.tsx
  src/components/DropdownMenu/index.tsx
  src/components/Header/index.tsx
  src/pages/PostEditPage/PostCreatePage/index.tsx
  src/pages/PostEditPage/PostUpdatePage/index.tsx
Labels: feature

#152 [FIX] Logout 기타 등등
  src/components/Avatar/AvatarStyled.ts
  src/components/Header/index.tsx
  src/pages/DetailPage/PostComment/index.tsx
Labels: fix

#153 [FEAT] 검색 페이지 구현
  src/components/Header/index.tsx
  src/hooks/useSelectedSearchedData.ts
  src/pages/mainPage/index.tsx
  src/slices/postList/utils.ts
  src/slices/searchedData/constants.ts
  src/slices/searchedData/index.ts
  src/slices/searchedData/searchedDataType.ts
  src/slices/searchedData/thunk.ts
  src/store/index.ts
Labels: feature

#154 [FEAT] 좋아요 버튼 기능 구현
  src/assets/LikeButtonIcon.svg
  src/assets/LikeButtonIcon.tsx
  src/components/LikeButton/index.tsx
  src/pages/DetailPage/index.tsx
Labels: feature

#155 [FEAT] 결과페이지 퍼센트 출력
  src/components/Avatar/AvatarProps.ts
  src/pages/DetailPage/PostComment/index.tsx
  src/pages/DetailPage/PostComment/useSelectedComment.ts
  src/pages/DetailPage/PostVote/index.tsx
  src/pages/DetailPage/PostVoteChart/BarChart.tsx
Labels: feature

#156 [FIX] Index, 404 반응형 단위 변경
  src/pages/Index.tsx
  src/pages/NotFound.tsx
  vercel.json
Labels: fix

#160 [FIX] 사용자 정보 없음 오류 해결 및 추가 리팩토링
  src/components/PostCard/PostSnippet.tsx
  src/pages/DetailPage/PostComment/index.tsx
  src/pages/DetailPage/PostVoteChart/BarChart.tsx
  src/pages/DetailPage/index.tsx
  src/pages/mainPage/index.tsx
  src/slices/postList/utils.ts
Labels: fix

#164 [Fix] Setting 수정 외 기타 등등
  src/assets/MailIcon.tsx
  src/components/Button/ImageUploadButton.tsx
  src/components/Button/StyledButton.ts
  src/components/Button/index.tsx
  src/components/Sign/In.tsx
  src/components/Sign/Up.tsx
  src/pages/SettingModal/Setting.tsx
  src/pages/userPage/SettingFollowButton.tsx
Labels: fix

#168 [Fix] 리팩토링 전 핫픽스
  src/components/Button/ImageUploadButton.tsx
  src/components/Button/index.tsx
  src/components/Header/index.tsx
  src/pages/SettingModal/Setting.tsx
Labels: fix

#175 [Refector] PostEditPage 리팩토링
  src/main.tsx
  src/pages/PostEditPage/Api.ts
  src/pages/PostEditPage/PostCreatePage/index.tsx
  src/pages/PostEditPage/PostUpdatePage/index.tsx
  src/pages/PostEditPage/VoteEditBox/index.tsx
  src/pages/PostEditPage/constants/index.ts
  src/pages/PostEditPage/formValidation.ts
  src/pages/mainPage/index.tsx
Labels: refactor

#178 [Refector] MainPage 리팩토링
  src/assets/RightArrowIcon.tsx
  src/components/NotificationCardBell/StyledNotification.ts
  src/components/NotificationCardBell/index.tsx
  src/components/Pagination/PaginationTypes.ts
  src/components/Pagination/index.tsx
  src/components/UserListCard/index.tsx
  src/hooks/useSelectedChannel.ts
  src/pages/mainPage/index.tsx
  src/slices/channel.ts
  src/slices/follow/thunk.ts
  src/slices/postList/utils.ts
  src/slices/searchedData/searchedDataType.ts
  src/types/APIResponseTypes.ts
Labels: feature, refactor

#174 [REFACTOR] Login page
  src/components/Input/PasswordInput.tsx
  src/components/Input/index.tsx
  src/components/Sign/In.tsx
  src/components/Sign/Up.tsx
  src/pages/Login.tsx
Labels: refactor

#176 [Refector] UserPage 리팩토링
  src/main.tsx
  src/pages/SettingPage/index.tsx
  src/pages/userPage/GrassTable.tsx
  src/pages/userPage/SettingFollowButton.tsx
  src/pages/userPage/UserInfo.tsx
  src/pages/userPage/UserPostList.tsx
  src/pages/userPage/index.tsx
Labels: refactor

#177 [FIX] Header, Footer 스타일링 수정
  src/components/Footer/index.tsx
  src/components/Header/StyledHeader.ts
  src/components/Header/index.tsx
  src/pages/mainPage/StyledMain.ts
Labels: fix

#183 [Refactor] : props 타입스크립트 파일명 변경 및 styled확장자 tsx로 변경
  src/components/Common/Avatar/styledAvatar.tsx
  src/components/Common/Badge/styledBadge.tsx
  src/components/Common/Button/ButtonProps.ts
  src/components/Common/Button/ImageUploadButton.tsx
  src/components/Common/Button/index.tsx
  src/components/Common/Button/styledButton.tsx
  src/components/Common/Card/CardProps.ts
  src/components/Common/Dropdown/DropdownProps.ts
  src/components/Common/Dropdown/index.tsx
  src/components/Common/Input/styledInput.tsx
  src/components/Common/OnlineBadge/OnlineBadgeProps.ts
  src/components/Common/OnlineBadge/index.tsx
  src/components/Common/OnlineBadge/styledBadge.tsx
  src/components/Common/Pagination/PaginationProps.ts
  src/components/Common/Pagination/index.tsx
  src/components/Common/Pagination/styledPagination.tsx
  src/components/Common/ScrollBar/styledScrollBar.tsx
  src/components/Common/index.ts
  src/components/Footer/styledFooter.tsx
  src/components/Header/index.tsx
  src/components/Header/mockChannels.ts
  src/components/Header/styledHeader.tsx
  src/components/Main/UserListCard/UserListCardProps.ts
  src/components/Main/UserListCard/index.tsx
  src/components/Main/UserListCard/mockUsers.ts
  src/components/Main/UserSnippet/styledUserSnippet.tsx
  src/components/NotificationCardBell/mockNotifications.ts
  src/components/NotificationCardBell/styledNotification.tsx
  src/components/Post/Detail/Comment/styledComment.tsx
  src/components/Post/Detail/Content/styledContent.tsx
  src/components/Post/Detail/Result/styledBarChart.tsx
  src/components/Post/Detail/Vote/styledVote.tsx
  src/components/PostCard/PostCardProps.ts
  src/components/PostCard/PostSnippet.tsx
  src/components/PostCard/index.tsx
  src/components/PostCard/styledPostCard.tsx
  src/components/Setting/styledSetting.tsx
  src/components/Sign/SignStyle.tsx
  src/components/User/styledUser.tsx
  src/hooks/usePagination.ts
  src/pages/PostCreate.tsx
  src/pages/PostUpdate.tsx
  src/slices/postList/utils.ts
Labels: refactor

#188 [Refactor] props 정리
  src/components/Common/Badge/BadgeProps.ts
  src/components/Common/Badge/index.tsx
  src/components/Common/Button/ButtonProps.ts
  src/components/Common/Button/index.tsx
  src/components/Common/Input/InputProps.ts
  src/components/Common/Input/PasswordInput.tsx
  src/components/Common/Input/index.tsx
  src/components/Common/Text/TextProps.ts
  src/components/Common/Text/index.tsx
  src/components/Main/PostCard/PostSnippet.tsx
  src/components/common/Badge/style.tsx
  src/components/common/Button/style.tsx
  src/components/layout/Header/index.tsx
Labels: refactor

#189 [Refector] 커스텀 axios 함수 적용
  src/components/Common/Button/ImageUploadButton.tsx
  src/components/Post/Detail/Comment/Item/Item.tsx
  src/components/Post/Detail/Comment/index.tsx
  src/components/Post/Detail/Content/index.tsx
  src/components/Post/Detail/LikeButton/index.tsx
  src/components/Post/Detail/Vote/index.tsx
  src/components/Setting/index.tsx
  src/components/Sign/In/index.tsx
  src/components/Sign/Up/index.tsx
  src/components/User/FollowButton/index.tsx
  src/components/layout/Header/NotificationCardBell/index.tsx
  src/components/layout/Header/index.tsx
  src/pages/DetailPage/index.tsx
  src/pages/IndexPage/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/SettingPage/index.tsx
  src/slices/channel.ts
  src/slices/follow/thunk.ts
  src/slices/loading/index.ts
  src/slices/notification/thunk.ts
  src/slices/postDetail.ts
  src/slices/postList/thunks.ts
  src/slices/searchedData/thunk.ts
  src/slices/user.ts
  src/slices/userList/thunk.ts
  src/store/index.ts
  src/utils/customAxios.ts
Labels: refactor

#192 [Refector] 메인페이지 컴포넌트 분리
  src/components/Main/Pagination/index.tsx
  src/components/Main/Pagination/type.ts
  src/components/Main/PostCard/PostSnippet/index.tsx
  src/components/Main/PostCard/PostSnippet/style.tsx
  src/components/Main/PostCard/PostSnippet/type.tsx
  src/components/Main/PostCard/index.tsx
  src/components/Main/PostCard/style.tsx
  src/components/Main/PostCard/type.ts
  src/components/Main/UserListCard/UserSnippet/index.tsx
  src/components/Main/UserListCard/UserSnippet/style.tsx
  src/components/Main/UserListCard/UserSnippet/type.ts
  src/components/Main/UserListCard/index.tsx
  src/components/Main/UserListCard/type.ts
  src/components/Main/style.tsx
  src/hooks/usePagination.ts
  src/slices/postList/utils.ts
Labels: refactor

#202 [FEAT] meta tag 추가
  index.html
  vercel.json
Labels: feature

#200 [FIX] 알림 초기 값으로 1이 보였다가 사라지는 현상 수정
  src/pages/MainPage/index.tsx
  src/slices/notification/index.ts
Labels: fix

#204 [FIX] 유저 페이지 (잔디, follow) 수정
  src/components/User/FollowButton/index.tsx
  src/components/User/GrassTable/index.tsx
  src/components/User/GrassTable/style.tsx
Labels: fix

#207 [FEAT] LoginPage 뒤로가기 추가
  src/pages/SignPage/index.tsx
  src/pages/SignPage/style.tsx
Labels: feature

#212 [FEAT] 서치바 버튼 입력 기능 추가
  src/components/layout/Header/index.tsx
  src/components/layout/Header/style.tsx
Labels: feature

#218 [FEAT] Admin page, ProtectedRoute
  index.html
  src/assets/PlusIcon.svg
  src/assets/RightArrowIcon.tsx
  src/components/common/ProtectedRoute/index.tsx
  src/components/common/ProtectedRoute/type.ts
  src/components/layout/Header/NotificationCardBell/index.tsx
  src/components/layout/Header/NotificationCardBell/type.ts
  src/components/layout/Header/index.tsx
  src/components/layout/Header/style.tsx
  src/hooks/usePagination.ts
  src/main.tsx
  src/pages/AdminPage/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/RequestListPage/RequestList.tsx
  src/pages/RequestPage/index.tsx
Labels: feature

#213 [Refactor] Detail페이지 UX리팩토링
  src/components/Post/Detail/Result/index.tsx
  src/components/Post/Detail/Vote/index.tsx
Labels: refactor

#214 [FEAT] 다크모드 설정
  src/assets/Bell.tsx
  src/assets/DarkIcon.tsx
  src/assets/LightIcon.tsx
  src/assets/LikeButtonIcon.tsx
  src/assets/MailIcon.tsx
  src/assets/RightArrowIcon.tsx
  src/components/Main/Pagination/index.tsx
  src/components/Main/PostCard/PostSnippet/index.tsx
  src/components/Main/PostCard/index.tsx
  src/components/Main/UserListCard/UserSnippet/style.tsx
  src/components/Post/Detail/Comment/Item/Item.tsx
  src/components/Post/Detail/Comment/index.tsx
  src/components/Post/Detail/Content/index.tsx
  src/components/Post/Detail/Content/style.tsx
  src/components/User/GrassTable/style.tsx
  src/components/User/UserPostList/index.tsx
  src/components/common/Avatar/style.tsx
  src/components/common/Button/style.tsx
  src/components/common/Card/index.tsx
  src/components/common/Dropdown/style.tsx
  src/components/common/Input/style.tsx
  src/components/common/Text/index.tsx
  src/components/layout/Footer/style.tsx
  src/components/layout/Header/DarkModeToggle/index.tsx
  src/components/layout/Header/NotificationCardBell/index.tsx
  src/components/layout/Header/NotificationCardBell/style.tsx
  src/components/layout/Header/index.tsx
  src/main.tsx
  src/pages/IndexPage/style.tsx
  src/pages/NotFoundPage/style.tsx
  src/pages/PostPage/style.ts
  src/pages/SettingPage/style.tsx
  src/pages/SignPage/style.tsx
  src/styles/GlobalStyle.ts
  src/styles/theme.ts
Labels: feature

#221 [FEAT] 투표 항목 변경 막기
  src/components/Post/Edit/FormContent/index.tsx
  src/components/Post/Edit/VoteBox/index.tsx
  src/components/Post/Edit/VoteBox/style.tsx
  src/components/Post/Edit/VoteBox/type.ts
  src/components/Post/Edit/useSelectedPost.ts
  src/pages/PostPage/index.tsx
  src/pages/UpdatePage/index.tsx
Labels: feature

#225 [FIX] User 폼 리뷰 반영
  src/components/User/UserPostList/index.tsx
  src/pages/SettingPage/index.tsx
  src/pages/UserPage/style.tsx
Labels: fix

#227 [FIX]update페이지 서버데이터의 channelId로 변경
  src/components/Post/Detail/Content/index.tsx
  src/components/layout/Header/NotificationCardBell/index.tsx
  src/components/layout/Header/index.tsx
  src/main.tsx
  src/pages/UpdatePage/index.tsx
Labels: fix

#228 [FEAT] 요청별 로딩 처리
  src/hooks/useSelectedStatus.ts
  src/pages/MainPage/index.tsx
  src/slices/loading/index.ts
  src/slices/status/index.ts
  src/slices/status/type.ts
  src/store/index.ts
  src/utils/customAxios.ts
  src/utils/customAxios/constants.ts
  src/utils/customAxios/index.ts
  src/utils/customAxios/type.ts
  src/utils/customAxios/utils.ts
Labels: feature

#229 [Refector] Input 디자인 및 레이아웃 수정
  src/components/Post/Detail/Vote/index.tsx
  src/components/Post/Edit/FormContent/index.tsx
  src/components/Post/Edit/VoteBox/index.tsx
  src/components/Sign/In/index.tsx
  src/components/Sign/Up/index.tsx
  src/components/common/Dropdown/style.tsx
  src/components/common/Input/index.tsx
  src/components/common/Input/style.tsx
  src/components/common/Input/type.ts
  src/components/layout/Header/index.tsx
  src/pages/PostPage/style.ts
Labels: refactor

#237 [Refactor] 비밀번호 관련 리팩토링
  src/components/Setting/Password/index.tsx
  src/components/Setting/UserInfo/index.tsx
  src/components/Setting/index.tsx
  src/components/Setting/style.tsx
  src/components/Sign/Up/index.tsx
  src/components/common/Dropdown/style.tsx
  src/components/layout/Header/index.tsx
  src/main.tsx
  src/pages/SettingPage/index.tsx
  src/pages/SettingPage/style.tsx
  src/utils/customAxios/constants.ts
Labels: refactor

#233 [FEAT] 유저 페이지 페이지네이션 적용
  src/components/User/UserPostList/index.tsx
Labels: feature

#236 [FEAT] Admin, request Page 제작
  package-lock.json
  package.json
  src/assets/DarkIcon.tsx
  src/assets/LightIcon.tsx
  src/components/Post/Detail/Result/BarChart/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Input/style.tsx
  src/components/common/OnlineBadge/index.tsx
  src/components/common/OnlineBadge/style.tsx
  src/components/common/ProtectedRoute/index.tsx
  src/components/layout/Header/index.tsx
  src/components/layout/Header/style.tsx
  src/main.tsx
  src/pages/AdminPage/index.tsx
  src/pages/AdminPage/style.ts
  src/pages/RequestListPage/RequestList.tsx
  src/pages/RequestPage/index.tsx
  src/pages/RequestPage/style.ts
  src/styles/GlobalStyle.ts
Labels: feature

#238 [FEAT] Index 페이지 소개 추가
  index.html
  public/SlideD0.jpg
  public/SlideD1.jpg
  public/SlideD2.jpg
  public/SlideD3.jpg
  public/SlideD4.jpg
  public/SlideL0.jpg
  public/SlideL1.jpg
  public/SlideL2.jpg
  public/SlideL3.jpg
  public/SlideL4.jpg
  public/favicon.ico
  public/vite.svg
  src/components/Index/index.tsx
  src/components/Index/style.tsx
  src/pages/IndexPage/index.tsx
  src/pages/IndexPage/style.tsx
Labels: feature

#240 [FIX] 알림 ui, 데이터, 오류 수정
  src/components/Main/UserListCard/UserSnippet/index.tsx
  src/components/Main/UserListCard/UserSnippet/type.ts
  src/components/Post/Detail/LikeButton/index.tsx
  src/components/common/ScrollBar/style.tsx
  src/components/layout/Header/NotificationCardBell/index.tsx
  src/components/layout/Header/NotificationCardBell/style.tsx
  src/hooks/useSelectedPostListById.ts
  src/slices/postList/index.ts
  src/slices/postList/thunks.ts
  src/slices/postList/type.ts
  src/slices/userList/utils.ts
Labels: fix, refactor

#241 [Feat] 툴팁 컴포넌트 제작 및 적용
  src/components/User/GrassTable/index.tsx
  src/components/User/UserInfo/index.tsx
  src/components/common/Tooltip/TooltipArrow.tsx
  src/components/common/Tooltip/index.tsx
  src/components/common/Tooltip/style.tsx
  src/components/common/Tooltip/type.tsx
  src/types/APIResponseTypes.ts
Labels: feature

#242 [Refactor] detail페이지 리팩토링
  src/components/Main/PostCard/PostSnippet/index.tsx
  src/components/Main/PostCard/PostSnippet/type.tsx
  src/components/Main/PostCard/index.tsx
  src/components/Main/PostCard/type.ts
  src/components/Post/Detail/Comment/Item/Item.tsx
  src/components/Post/Detail/Comment/Item/index.tsx
  src/components/Post/Detail/Content/index.tsx
  src/components/User/UserInfo/index.tsx
  src/components/User/UserInfo/style.tsx
  src/components/common/Image/index.tsx
  src/components/layout/Header/index.tsx
  src/pages/SettingPage/index.tsx
  src/pages/SettingPage/style.tsx
Labels: refactor

#247 [Feat] postEditPage ui 수정
  src/components/Post/Edit/FormContent/index.tsx
  src/components/Post/Edit/FormContent/style.tsx
  src/components/common/Dropdown/style.tsx
  src/components/common/Input/index.tsx
  src/components/common/Input/style.tsx
  src/components/common/Input/type.ts
  src/pages/PostPage/style.ts
Labels: feature

#245 [FEAT} Loading spinner
  package-lock.json
  package.json
  src/components/Post/Edit/VoteBox/index.tsx
  src/components/Post/Edit/VoteBox/style.tsx
  src/components/User/UserInfo/index.tsx
  src/components/User/UserPostList/index.tsx
  src/components/common/MainPageSpinner/index.tsx
  src/components/common/MainPageSpinner/style.ts
  src/components/layout/Header/index.tsx
  src/components/layout/Header/style.tsx
  src/hooks/useSelectedStatus.ts
  src/pages/MainPage/index.tsx
  src/slices/postList/thunks.ts
  src/utils/customAxios/utils.ts
Labels: feature, fix

#256 [Feat] Post, Update page 새로고침 에러 수정
  src/components/Post/Detail/Content/index.tsx
  src/components/Post/Edit/FormContent/index.tsx
  src/pages/PostPage/index.tsx
  src/pages/UpdatePage/index.tsx
  src/utils/Validations/formValidation.ts
Labels: refactor

#255 [FIX] 아이콘 svg 변경
  src/assets/BellIcon.svg
  src/assets/BellIcon.tsx
  src/assets/CheckIcon.svg
  src/assets/DarkIcon.tsx
  src/assets/DeleteIcon.svg
  src/assets/DeleteIcon.tsx
  src/assets/DownArrowIcon.svg
  src/assets/HideEyesIcon.tsx
  src/assets/InfoIcon.svg
  src/assets/LeftArrowIcon.tsx
  src/assets/LightIcon.tsx
  src/assets/LikeButtonIcon.svg
  src/assets/LikeButtonIcon.tsx
  src/assets/MailIcon.tsx
  src/assets/MinusIcon.svg
  src/assets/PlusIcon.svg
  src/assets/PlusIcon.tsx
  src/assets/RightArrowIcon.svg
  src/assets/RightArrowIcon.tsx
  src/assets/SearchIcon.tsx
  src/assets/TitleLogo.svg
  src/assets/TrashCanIcon.svg
  src/assets/UserIcon.svg
  src/assets/ViewEyesIcon.tsx
  src/assets/react.svg
  src/components/Post/Edit/VoteBox/index.tsx
  src/components/Setting/Password/index.tsx
  src/components/Setting/UserInfo/index.tsx
  src/components/Sign/In/index.tsx
  src/components/Sign/Up/index.tsx
  src/components/Sign/style.tsx
  src/components/common/Avatar/style.tsx
  src/components/common/Badge/style.tsx
  src/components/common/Button/ImageUploadButton.tsx
  src/components/common/Button/index.tsx
  src/components/common/Button/style.tsx
  src/components/common/Button/types.ts
  src/components/common/Card/index.tsx
  src/components/common/Input/PasswordInput.tsx
  src/components/common/Input/style.tsx
  src/components/common/OnlineBadge/style.tsx
  src/components/common/Tooltip/TooltipArrow.tsx
  src/components/common/Tooltip/style.tsx
  src/components/layout/Header/DarkModeToggle/index.tsx
  src/components/layout/Header/NotificationCardBell/index.tsx
  src/components/layout/Header/index.tsx
  src/components/layout/Header/style.tsx
  src/main.tsx
  src/pages/AdminPage/style.ts
  src/pages/RequestPage/style.ts
  src/pages/SignPage/index.tsx
  src/pages/SignPage/style.tsx
  src/styles/theme.ts
Labels: fix

#260 [FIX] 코드 미복구
  src/main.tsx
Labels: fix

#264 [Fix] Dropdown
  src/components/Sign/Up/index.tsx
  src/components/layout/Header/index.tsx
  src/pages/SignPage/index.tsx
Labels: fix

#266 [Refector] 메인 페이지 리팩토링
  src/components/Main/ContentHeader/index.tsx
  src/components/Main/ContentHeader/style.tsx
  src/components/Main/PostCard/PostSnippet/index.tsx
  src/components/Main/PostCard/PostSnippet/type.tsx
  src/components/Main/PostCard/index.tsx
  src/components/Main/PostCard/style.tsx
  src/components/Main/PostCard/type.ts
  src/components/Main/PostList/PostCard/index.tsx
  src/components/Main/PostList/PostCard/style.tsx
  src/components/Main/PostList/PostCard/type.ts
  src/components/Main/PostList/index.tsx
  src/components/Main/UserList/UserGroup/index.tsx
  src/components/Main/UserList/UserGroup/style.tsx
  src/components/Main/UserList/UserGroup/type.ts
  src/components/Main/UserList/UserSnippet/index.tsx
  src/components/Main/UserList/UserSnippet/type.ts
  src/components/Main/UserList/index.tsx
  src/components/Main/UserList/type.ts
  src/components/Main/UserListCard/type.ts
  src/components/Main/hooks/useChannelPosts.ts
  src/components/Main/hooks/useGetUsers.ts
  src/components/Main/hooks/useSearchPosts.ts
  src/components/User/UserPostList/index.tsx
  src/components/common/Pagination/index.tsx
  src/components/common/Pagination/style.tsx
  src/components/common/Pagination/type.ts
  src/components/layout/Header/NotificationCardBell/index.tsx
  src/hooks/usePagination.ts
  src/hooks/useSelectedMyInfo.ts
  src/hooks/useSelectedPostDetail.ts
  src/hooks/useSelectedSearchedData.ts
  src/hooks/useSelectedUserList.ts
  src/pages/MainPage/index.tsx
  src/slices/postList/utils.ts
  src/slices/userList/utils.ts
  src/utils/makeSnippet.ts
Labels: refactor

#268 [Feat] post update 추상화 & 리팩토링
  src/assets/DeleteIcon.tsx
  src/assets/PlusIcon.tsx
  src/assets/SearchIcon.tsx
  src/components/Post/Edit/FormContent/index.tsx
  src/components/Post/Edit/FormContent/style.tsx
  src/components/Post/Edit/PostForm/index.tsx
  src/components/Post/Edit/PostForm/style.ts
  src/components/Post/Edit/PostForm/type.ts
  src/components/Post/Edit/SubmitButton/index.tsx
  src/components/Post/Edit/SubmitButton/type.ts
  src/components/Post/Edit/UpdateForm/index.tsx
  src/components/Post/Edit/UpdateForm/type.ts
  src/components/Post/Edit/UserInfo/index.tsx
  src/components/Post/Edit/UserInfo/style.tsx
  src/components/Post/Edit/VoteBox/index.tsx
  src/components/Post/Edit/VoteBox/style.tsx
  src/main.tsx
  src/pages/PostPage/index.tsx
  src/pages/PostPage/style.ts
  src/pages/UpdatePage/index.tsx
  src/utils/constants.ts
Labels: refactor

#269 [FIX] follow, like 디바운싱 처리
  src/components/Post/Detail/LikeButton/index.tsx
  src/components/User/FollowButton/index.tsx
  src/components/layout/Header/NotificationCardBell/index.tsx
  src/main.tsx
  src/slices/follow/thunk.ts
  src/slices/notification/index.ts
  src/slices/notification/type.ts
Labels: feature, fix

#273 [Feat] whiteSpace 처리 기능 추가
  src/components/Post/Detail/Comment/index.tsx
  src/components/Post/Edit/FormContent/index.tsx
  src/components/Post/Edit/VoteBox/index.tsx
Labels: feature

#276 [Fix] user page tooltip 수정
  src/components/User/GrassTable/index.tsx
  src/components/User/UserInfo/index.tsx
  src/components/common/Tooltip/index.tsx
  src/components/common/Tooltip/style.tsx
  src/main.tsx
  src/types/APIResponseTypes.ts
Labels: feature, fix

#271 [FIX] 유저 리스트 ui 버그 수정
  src/components/Main/UserList/UserGroup/style.tsx
  src/components/Main/UserList/index.tsx
  src/pages/SignPage/index.tsx
Labels: fix, refactor

#274 [FIX] 미인증 사용자 userList 안보이는 버그 수정
  src/components/Main/hooks/useGetUsers.ts
Labels: fix

#280 [Refactor] DropDown 리팩토링
  src/components/common/Dropdown/index.tsx
  src/components/common/Dropdown/style.tsx
Labels: refactor

#279 [FIX] Input Alert 대신 Warning으로
  src/components/Post/Edit/FormContent/index.tsx
  src/components/Post/Edit/FormContent/style.tsx
  src/components/Setting/Password/index.tsx
  src/components/Setting/UserInfo/index.tsx
  src/components/Setting/style.tsx
  src/components/User/GrassTable/index.tsx
  src/components/User/GrassTable/style.tsx
  src/components/User/UserInfo/index.tsx
  src/components/User/UserInfo/style.tsx
  src/components/common/Avatar/style.tsx
  src/components/common/Button/ImageUploadButton.tsx
  src/components/common/Button/types.ts
  src/pages/SignPage/index.tsx
Labels: fix

#282 [Refector] header 컴포넌트 props 대신 리덕스 활용
  src/App.tsx
  src/components/layout/Header/index.tsx
  src/components/layout/Header/type.ts
  src/hooks/useSelectedChannel.ts
  src/hooks/useSelectedMyInfo.ts
  src/main.tsx
  src/slices/initialState.ts
  src/slices/type.ts
  src/slices/user.ts
  src/slices/user/type.ts
  src/types/APIResponseTypes.ts
Labels: refactor

#284 [Refector] Card 컴포넌트 레이아웃 수정
  src/components/Main/PostList/PostCard/index.tsx
  src/components/Post/Detail/Comment/Item/index.tsx
  src/components/Post/Detail/Result/BarChart/index.tsx
  src/components/Post/Detail/Vote/index.tsx
  src/components/Post/Edit/FormContent/style.tsx
  src/components/Sign/style.tsx
  src/components/common/Card/index.tsx
  src/pages/RequestPage/index.tsx
  src/pages/RequestPage/style.ts
  src/pages/SignPage/index.tsx
  src/pages/SignPage/style.tsx
Labels: refactor

#286 [Refector] 리덕스 슬라이스 타입 정리
  src/components/layout/Header/index.tsx
  src/hooks/useSelectedChannel.ts
  src/hooks/useSelectedMyInfo.ts
  src/hooks/useSelectedPostDetail.ts
  src/hooks/useSelectedSearchedData.ts
  src/hooks/useSelectedUserList.ts
  src/slices/channel.ts
  src/slices/channel/type.ts
  src/slices/follow/index.ts
  src/slices/follow/type.ts
  src/slices/initialState.ts
  src/slices/notification/index.ts
  src/slices/notification/type.ts
  src/slices/postDetail.ts
  src/slices/postDetail/type.ts
  src/slices/postList/index.ts
  src/slices/postList/type.ts
  src/slices/searchedData/index.ts
  src/slices/searchedData/type.ts
  src/slices/user.ts
  src/slices/user/type.ts
  src/slices/userList/index.ts
  src/slices/userList/type.ts
Labels: refactor

#288 [FIX] 알림창 글자 밀려나는 오류 수정
  src/components/Main/UserList/UserSnippet/index.tsx
  src/components/Main/UserList/UserSnippet/type.ts
  src/components/Main/UserList/index.tsx
  src/components/layout/Header/NotificationCardBell/index.tsx
  src/components/layout/Header/NotificationCardBell/type.ts
  src/utils/makeSnippet.ts
Labels: fix

#294 [FIX] 로딩시 몇가지 문제 해결
  src/components/Main/UserList/index.tsx
  src/components/layout/Header/index.tsx
  src/slices/notification/index.ts
  src/slices/postDetail.ts
  src/slices/postList/index.ts
  src/slices/searchedData/index.ts
  src/slices/user.ts
  src/slices/userList/index.ts
Labels: fix

#298 [Refactor] whitespace 처리 방법 변경
  src/components/Post/Detail/Comment/index.tsx
  src/components/Post/Edit/FormContent/index.tsx
  src/components/Post/Edit/VoteBox/index.tsx
  src/utils/Validations/formValidation.ts
Labels: refactor

#297 전체 코드 리뷰 중 누락된 부분 수정
  src/components/Index/index.tsx
  src/components/Main/PostList/PostCard/index.tsx
  src/components/Post/Detail/Comment/index.tsx
  src/components/Post/Detail/Comment/style.tsx
  src/components/Post/Detail/Content/index.tsx
  src/components/Post/Detail/Result/BarChart/index.tsx
  src/components/Post/Detail/Vote/index.tsx
  src/components/Post/Edit/FormContent/index.tsx
  src/components/Post/Edit/PostForm/index.tsx
  src/components/Post/Edit/VoteBox/index.tsx
  src/components/Setting/Password/index.tsx
  src/components/Setting/UserInfo/index.tsx
  src/components/User/GrassTable/index.tsx
  src/components/User/UserInfo/index.tsx
  src/components/common/Avatar/index.tsx
  src/components/common/Card/index.tsx
  src/components/common/Image/index.tsx
  src/components/common/Image/type.ts
  src/components/common/Pagination/index.tsx
  src/components/common/Tooltip/index.tsx
  src/components/common/index.ts
  src/components/layout/Header/index.tsx
Labels: refactor

#300 fix: #299 디바운싱 오류 수정
  src/components/Post/Detail/LikeButton/index.tsx
  src/components/User/FollowButton/index.tsx
  src/slices/follow/index.ts
Labels: fix

#309 [FIX] 디바운싱 예상되게 수정
  src/components/Post/Detail/LikeButton/index.tsx
  src/components/User/FollowButton/index.tsx
  src/components/User/UserPostList/index.tsx
  src/hooks/useSelectedPostListByUser.ts
  src/hooks/useSelectedUser.ts
  src/slices/user.ts
Labels: fix

#311 [Refector] 슬라이스 폴더 리팩토링
  src/components/Main/hooks/useGetUsers.ts
  src/components/Post/Detail/Comment/index.tsx
  src/components/Post/Detail/Vote/index.tsx
  src/components/Post/Edit/FormContent/index.tsx
  src/components/User/FollowButton/index.tsx
  src/components/User/UserInfo/index.tsx
  src/components/User/UserPostList/index.tsx
  src/components/common/Dropdown/index.tsx
  src/components/layout/Header/index.tsx
  src/hooks/useAxios.ts
  src/hooks/useLocalStorage.ts
  src/hooks/useRafState.ts
  src/hooks/useScroll.ts
  src/pages/AdminPage/index.tsx
  src/pages/DetailPage/index.tsx
  src/pages/PostPage/index.tsx
  src/pages/RequestPage/index.tsx
  src/pages/SettingPage/index.tsx
  src/pages/UpdatePage/index.tsx
  src/slices/channel/index.ts
  src/slices/channel/thunk.ts
  src/slices/constants.ts
  src/slices/follow/constants.ts
  src/slices/follow/index.ts
  src/slices/follow/thunk.ts
  src/slices/notification/constants.ts
  src/slices/notification/index.ts
  src/slices/notification/thunk.ts
  src/slices/postDetail/index.ts
  src/slices/postDetail/thunk.ts
  src/slices/postList/constants.ts
  src/slices/postList/index.ts
  src/slices/postList/thunks.ts
  src/slices/searchedData/constants.ts
  src/slices/searchedData/index.ts
  src/slices/searchedData/thunk.ts
  src/slices/user/index.ts
  src/slices/user/thunk.ts
  src/slices/userList/contants.ts
  src/slices/userList/index.ts
  src/slices/userList/thunk.ts
Labels: refactor

#317 [Fix] 관리자의 글/댓글 삭제 권한 추가
  src/components/Main/ContentHeader/index.tsx
  src/components/Main/ContentHeader/style.tsx
  src/components/Post/Detail/Comment/Item/index.tsx
  src/components/Post/Detail/Content/index.tsx
  src/components/Post/Detail/Result/BarChart/index.tsx
  src/components/Post/Detail/Vote/index.tsx
  src/components/layout/Header/DarkModeToggle/index.tsx
Labels: fix, refactor

#320 Fix/#319 protected route/yun
  package-lock.json
  package.json
  src/components/Index/style.ts
  src/components/Main/ContentHeader/style.ts
  src/components/Main/PostList/PostCard/style.ts
  src/components/Main/UserList/UserGroup/style.ts
  src/components/Main/style.ts
  src/components/Post/Detail/Comment/Item/style.ts
  src/components/Post/Detail/Comment/style.ts
  src/components/Post/Detail/Content/style.ts
  src/components/Post/Detail/Result/BarChart/style.ts
  src/components/Post/Detail/Vote/style.ts
  src/components/Post/Edit/FormContent/style.ts
  src/components/Post/Edit/UserInfo/style.ts
  src/components/Post/Edit/VoteBox/style.ts
  src/components/Setting/style.ts
  src/components/Sign/style.ts
  src/components/User/GrassTable/style.ts
  src/components/User/UserInfo/style.ts
  src/components/common/Avatar/style.ts
  src/components/common/Badge/style.ts
  src/components/common/Button/style.ts
  src/components/common/Dropdown/style.ts
  src/components/common/Input/style.ts
  src/components/common/OnlineBadge/style.ts
  src/components/common/Pagination/style.ts
  src/components/common/ProtectedRoute/index.tsx
  src/components/common/ScrollBar/style.ts
  src/components/common/Tooltip/style.ts
  src/components/common/Tooltip/type.ts
  src/components/layout/Footer/style.ts
  src/components/layout/Header/NotificationCardBell/index.tsx
  src/components/layout/Header/NotificationCardBell/style.ts
  src/components/layout/Header/index.tsx
  src/components/layout/Header/style.ts
  src/pages/DetailPage/style.ts
  src/pages/IndexPage/style.ts
  src/pages/MainPage/style.ts
  src/pages/NotFoundPage/style.ts
  src/pages/SettingPage/style.ts
  src/pages/SignPage/style.ts
  src/pages/UserPage/style.ts
Labels: fix, refactor

#322 [Docs] README 수정
  README.md
Labels: feature
